# Preprocessing of the TSC dataset

The index is managed by the NCRIS-funded Terrestrial Ecosystem Research Network (TERN) project at The University of Queensland and supported by the Australian Government Department of Climate Change, Energy, the Environment and Water (DCCEEW).

All TSX data available at https://tsx.org.au/tsx/ are openly accessible and are licensed under a Creative Commons – Attribution 4.0 International licence (CC BY 4.0).

Publication date of the data: 25-11-2025

The dataset contains:

1) 193,500 yearly population values (1950–2022) from 25,164 monitored time series, for 217 animal species and 178 plant taxa. Plants are left out in our database as we focus only on animals.

2) Per value the data contains: species, site, region, unit of measurement (there are 103 different possible units), year and the population 

3) There are 15,724 monitoring sites in 346 regions

For the purposes of our database, the dataset has been heavily filtered to match our schema.

In [125]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [126]:
load_dotenv()
password = os.getenv("DB_PASSWORD")
os.environ["DATABASE_URL"] = f"mysql+pymysql://root:{password}@localhost/animal_extinction_db"
engine = create_engine(os.environ["DATABASE_URL"])

In [ ]:
# Threatened Species Index
tsx = pd.read_csv("Data/tsx.csv", dtype=str, low_memory=False)

In [128]:
print(list(tsx.columns))

['ID', 'Binomial', 'SpNo', 'TaxonID', 'CommonName', 'Class', 'Order', 'Family', 'FamilyCommonName', 'Genus', 'Species', 'Subspecies', 'FunctionalGroup', 'TaxonomicGroup', 'EPBCStatus', 'IUCNStatus', 'BirdActionPlanStatus', 'MaxStatus', 'State', 'Region', 'RegionCentroidLatitude', 'RegionCentroidLongitude', 'RegionCentroidAccuracy', 'SiteID', 'SourceID', 'SourceDesc', 'MonitoringProgram', 'UnitID', 'Unit', 'SearchTypeID', 'SearchTypeDesc', 'ResponseVariableType', 'DataType', '1950', '1951', '1952', '1953', '1954', '1955', '1956', '1957', '1958', '1959', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', 'TimeSeriesLength', 'TimeSeriesSampleYears', 'TimeSeriesCompleteness', 'TimeSeriesSamplingEvenness', 'AbsencesRecorded', 'StandardisationOfMethodEffort', 'ObjectiveOfMonitoring', 'SpatialRepresentativeness', 'ConsistencyOfMonitoring', 'Management', 'ManagementCategory', 'ManagementCategoryComments', 'SuppressAggregatedData', 'SurveyCount', 'TimeSeriesID', 'NationalPriorityTaxa', 'Citation']

In [129]:
# Filter only relevant columns = all years + selected animal info
years = [str(y) for y in range(1950, 2023)]

keep = ['Binomial', 'CommonName', 'TaxonomicGroup', 'EPBCStatus', 'State', 'ResponseVariableType', 'Unit', "Class"] + years
tsx = tsx[keep]
tsx.head()

,Binomial,CommonName,TaxonomicGroup,EPBCStatus,State,ResponseVariableType,Unit,Class,1950,1951,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Charadrius_mongolus,Lesser Sand Plover,Birds,Endangered,Western Australia,Average count,Sample: abundance (counts),Aves,NaN,NaN,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,Charadrius_mongolus,Lesser Sand Plover,Birds,Endangered,Western Australia,Average count,Sample: abundance (counts),Aves,NaN,NaN,...,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN
2,Charadrius_mongolus,Lesser Sand Plover,Birds,Endangered,Western Australia,Average count,Sample: abundance (counts),Aves,NaN,NaN,...,2.0,0.0,0.0,2.0,8.0,1.0,NaN,NaN,NaN,NaN
3,Charadrius_mongolus,Lesser Sand Plover,Birds,Endangered,Western Australia,Average count,Sample: abundance (counts),Aves,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Charadrius_mongolus,Lesser Sand Plover,Birds,Endangered,Western Australia,Average count,Sample: abundance (counts),Aves,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN

In [130]:
# Filter out all species that are not animals
tsx = tsx[tsx['TaxonomicGroup'] != 'Plants'].reset_index(drop=True)

In [131]:
# inspect the units
print(tsx['Unit'].unique())
print(tsx['ResponseVariableType'].unique())

<StringArray>
[                                                                                                                              'Sample: abundance (counts)',
                                                                                                                          'Sample: abundance (call counts)',
                                                                                                                             'Proxy: count of spawn masses',
                                                                                    'Proxy: estimated population abundance by a mixed mark-recapture model',
                                                                                                                                                'Occupancy',
                                                                                                                      'Proxy: Log tadpole catch per minute',
                                                                                                                       'Sample: detection or non-detection',
                                                                                        'Proxy: Estimated historic changes in proportion of sites occupied',
                                                                                                            'Counts as a percentage of a previous estimate',
                                                                                                                                    'Proxy: recorded calls',
                                                                                                                                       'Occupancy estimate',
                                                                            'Trapping success: number of encounters (captures) per 7 trap nights of effort',
 'Modelled predicted values of calf abundance expressed per surveyed km (inter-annual values represent model output rather than multiple surveys per year)',
                                                                                                                 'detections per 100 trap nights of effort',
                                                                  'Sample: trapping success: number of encounters (captures) per 100 trap nights of effort',
                                                         'Sample: density (counts/fixed areas) calculated by spatially explicit capture-recapture analysis',
                                                                                                                     'Sample: density (counts/fixed areas)',
                                                                                                                                    'Adjusted Trap Success',
                                                            'Proxy: modelled estimate of total population abundance by distance analysis for both islands.',
                                                                                                                   'Non-repeat animals trapped per session',
                                                                                                                  'Occupancy: Proportion of sites detected',
                                                                                                                      'Sample: density (counts/fixed area)',
                                                                                                                                      'track counts per km',
                                                                                                                             'Sample: number of bilbies/km',
                                                                                                                    'Sample: density (individuals per km2)',
                                                                                                                                     'Individuals captured',
                              'Sample: Occupancy (# presences/# surveys = trapping success: number of encounters (captures) per 100 trap nights of effort)',
                                                                         'Trapping success: number of encounters (captures) per 100 trap nights of effort)',
                                                                                                                   'Sightings per 100km of driven transect',
                                                                                                                                    'Proxy: pup production',
                                                                                                                'Sample: Occupancy (# presences/# surveys)',
                                                                                                                                'Minimum known to be alive',
                                                                                               'Sample: Average number of animals seen per night of survey',
                                                                                                          'group sighting (could include adults or calves)',
                                                                                                                                       'abundance (counts)',
                                                                          'Trapping success: number of encounters (captures) per 100 trap nights of effort',
                                                                                                                                                    'Index',
                                                                                                                        'Occupancy (# presences/# surveys)',
                                                                                                           'Naive occupancy (proportion of sites occupied)',
                                                                                                           'Number of species images totalled for the year',
                                                                                                                     'Occupancy: Percent of sites detected',
                                                                                    'Trapping success: number of individuals per 100 trap nights of effort',
                                                                                                                    'Mean annual detection per km surveyed',
                                                                                                                    'trapping capture success/capture rate',
                                                                                                      'Proportion of surveyed sites with presence detected',
                                                                                                         'Abundance estimate based on spline interpolation',
                                                                                                                                 'Individuals per transect',
                                                                                                                                      'Individuals per km2',
                                                                                                        'Sample: Non-repeat animals trapped per trap night',
                                                                             'trapping success: total captures / trap effort (total trap nights per annum)',
                   'Sample: Occupancy (# presences/# surveys = trapping success: number of encounters (captures) of females per 100 trap nights of effort)',
                     'Sample: Occupancy (# presences/# surveys = trapping success: number of encounters (captures) of males per 100 trap nights of effort)',
                                                                                                'Proportion of surveyed sites that had animal tracks/signs',
                                                                                                           'Percent trap success of individuals (as ratio)',
                                                                                  'Kowari (minimum # known to be alive) / distance travelled (km) per year',
                                                                                                                             'Sample: density (counts/km2)',
                                                                                           'Sample: abundance (counts) - effort-based observational counts',
                                                                                                                                'Number of Nesting Females',
                                                                                                          'Individuals captured per 100 survey plot nights',
                                                                                                                                   'Proxy: number of nests',
                                                                                          'Proxy: estimated population abundance by a mark-recapture model',
                                                                                                         'Proxy: burrow estimate based on transect density',
                                                                                                                 'Population estimate from adjusted counts',
                                                                                                                                             'Proxy: nests',
                                                                                                                                    'Proxy: breeding pairs',
                                                                                                                     'Sample: density (individuals per ha)',
                                                                                                    'Average number of sightings per 1km transect surveyed',
                                                                                                                 'Mean number of calls per positive survey',
                                                                                                                  'Territory density (territories per km2)',
                                                                                                         'Sample: count of seen individuals after playback',
                                                                                                              'Modelled estimate of whole island abundance',
                                                                                                                     'Proportion of surveyed mounds active',
                                                                                                                                         'Proxy: eggs laid',
                                                                                                                      'Proxy: count of pre-fledging chicks',
                                                                                                                                    'Proxy: chicks fledged',
                                                                                                              'Proxy: population estimate based on banding']
Length: 76, dtype: str
<StringArray>
['Average count', 'Reporting rate', 'Maximum count']
Length: 3, dtype: str

In [132]:
# Keeping only counts
tsx = tsx[tsx['Unit'].str.contains('abundance (counts)', regex=False, na=False)]

In [133]:
tsx["Binomial"] = tsx["Binomial"].str.replace("_", " ").str.strip()

tsx.head()

,Binomial,CommonName,TaxonomicGroup,EPBCStatus,State,ResponseVariableType,Unit,Class,1950,1951,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Charadrius mongolus,Lesser Sand Plover,Birds,Endangered,Western Australia,Average count,Sample: abundance (counts),Aves,NaN,NaN,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,Charadrius mongolus,Lesser Sand Plover,Birds,Endangered,Western Australia,Average count,Sample: abundance (counts),Aves,NaN,NaN,...,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN
2,Charadrius mongolus,Lesser Sand Plover,Birds,Endangered,Western Australia,Average count,Sample: abundance (counts),Aves,NaN,NaN,...,2.0,0.0,0.0,2.0,8.0,1.0,NaN,NaN,NaN,NaN
3,Charadrius mongolus,Lesser Sand Plover,Birds,Endangered,Western Australia,Average count,Sample: abundance (counts),Aves,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Charadrius mongolus,Lesser Sand Plover,Birds,Endangered,Western Australia,Average count,Sample: abundance (counts),Aves,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN

In [134]:
print(tsx['EPBCStatus'].unique())

<StringArray>
['Endangered', 'Vulnerable', nan, 'Critically Endangered']
Length: 4, dtype: str

In [135]:
level={"Least Concern":"LC","Near Threatened":"NT", "Vulnerable":"VU", "Endangered":"EN", "Critically Endangered":"CR", "Conservation Dependent":"CD", 
       "Extinct in the Wild":"EW", "Extinct":"EX", "Data Deficient":"DD", "Not Evaluated":"NE"}

tsx["Level"] = None

for index, row in tsx.iterrows():
    tsx.loc[index, "Level"] = level.get(row["EPBCStatus"], None)

tsx.head()

,Binomial,CommonName,TaxonomicGroup,EPBCStatus,State,ResponseVariableType,Unit,Class,1950,1951,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,Level
0,Charadrius mongolus,Lesser Sand Plover,Birds,Endangered,Western Australia,Average count,Sample: abundance (counts),Aves,NaN,NaN,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,EN
1,Charadrius mongolus,Lesser Sand Plover,Birds,Endangered,Western Australia,Average count,Sample: abundance (counts),Aves,NaN,NaN,...,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,EN
2,Charadrius mongolus,Lesser Sand Plover,Birds,Endangered,Western Australia,Average count,Sample: abundance (counts),Aves,NaN,NaN,...,0.0,0.0,2.0,8.0,1.0,NaN,NaN,NaN,NaN,EN
3,Charadrius mongolus,Lesser Sand Plover,Birds,Endangered,Western Australia,Average count,Sample: abundance (counts),Aves,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,EN
4,Charadrius mongolus,Lesser Sand Plover,Birds,Endangered,Western Australia,Average count,Sample: abundance (counts),Aves,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,EN

In [136]:
years = [str(y) for y in range(1950, 2023)]
keep_cols = ["Binomial", "CommonName", "Class", "State", "Level"] + years

tsx = tsx[keep_cols]

In [137]:
tsx = tsx.rename(columns={"Binomial": "Scientific Name", "CommonName": "Common_Name"})
tsx.head()

,Scientific Name,Common_Name,Class,State,Level,1950,1951,1952,1953,1954,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Charadrius mongolus,Lesser Sand Plover,Aves,Western Australia,EN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,Charadrius mongolus,Lesser Sand Plover,Aves,Western Australia,EN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN
2,Charadrius mongolus,Lesser Sand Plover,Aves,Western Australia,EN,NaN,NaN,NaN,NaN,NaN,...,2.0,0.0,0.0,2.0,8.0,1.0,NaN,NaN,NaN,NaN
3,Charadrius mongolus,Lesser Sand Plover,Aves,Western Australia,EN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Charadrius mongolus,Lesser Sand Plover,Aves,Western Australia,EN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN

In [138]:
# Converting the populations into double data type
years = [str(y) for y in range(1950, 2023)]
tsx[years] = tsx[years].apply(pd.to_numeric, errors="coerce").astype("float64")
tsx[years].dtypes

1950    float64
1951    float64
1952    float64
1953    float64
1954    float64
         ...
2018    float64
2019    float64
2020    float64
2021    float64
2022    float64
Length: 73, dtype: object

In [ ]:
# Sum the populations of one animal in one state
# -> there are multiple measurements as the animals are monitored in multiple locations within the state

years = [str(y) for y in range(1950, 2023)]

loc_sums = (
    tsx.groupby(["Scientific Name", "Common_Name", "Class", "State", "Level"], as_index=False)[years]
      .sum(min_count=1)
)

loc_sums.head()

loc_sums.shape

(141, 78)

In [ ]:
# Saving the preprocessing for later database insertion

loc_sums.to_csv("Data/tsx_cleaned.csv")